# Generated by Django 2.2 on 2019-04-08 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=30, verbose_name='姓名')),
                ('age', models.IntegerField(db_column='age', verbose_name='年龄')),
                ('intro', models.CharField(db_column='intro', max_length=400, verbose_name='介绍')),
            ],
            options={
                'verbose_name': 'story',
                'verbose_name_plural': '故事',
                'db_table': 'story',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(db_column='content', verbose_name='详情')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.Story')),
            ],
            options={
                'verbose_name': 'story',
                'verbose_name_plural': '详情',
                'db_table': 'content',
            },
        ),
    ]
