# Generated by Django 2.2 on 2019-04-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='intro',
            field=models.TextField(db_column='intro', verbose_name='介绍'),
        ),
    ]
