# Generated by Django 2.2 on 2019-04-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_auto_20190408_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.CharField(db_column='content', max_length=1000, verbose_name='详情'),
        ),
        migrations.AlterField(
            model_name='story',
            name='intro',
            field=models.CharField(db_column='intro', max_length=1000, verbose_name='介绍'),
        ),
    ]
