# Generated by Django 2.2 on 2019-04-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_auto_20190408_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(db_column='content', verbose_name='详情'),
        ),
        migrations.AlterField(
            model_name='story',
            name='intro',
            field=models.TextField(db_column='intro', verbose_name='介绍'),
        ),
        migrations.AlterField(
            model_name='story',
            name='name',
            field=models.TextField(db_column='name', verbose_name='姓名'),
        ),
    ]
