# Generated by Django 2.2 on 2019-04-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_auto_20190408_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='name',
            field=models.CharField(db_column='name', max_length=40, verbose_name='姓名'),
        ),
    ]
