# Generated by Django 2.2 on 2019-04-10 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_auto_20190410_2058'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='content',
            table='storyContent',
        ),
    ]
