# Generated by Django 2.2 on 2019-04-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0008_auto_20190410_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='videoUrl',
            field=models.CharField(db_column='videoUrl', max_length=200, null=True, verbose_name='视频地址'),
        ),
    ]
