# Generated by Django 2.2 on 2019-05-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(db_column='province', max_length=40, verbose_name='province')),
                ('city', models.CharField(db_column='city', max_length=40, verbose_name='city')),
                ('name', models.CharField(db_column='name', max_length=500, verbose_name='name')),
            ],
            options={
                'verbose_name': 'school',
                'verbose_name_plural': '机构',
                'db_table': 'school',
            },
        ),
    ]
