# Generated by Django 2.2 on 2019-05-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(db_column='city', max_length=40, null=True, verbose_name='city'),
        ),
    ]
