# Generated by Django 2.2 on 2019-05-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20190515_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, db_column='city', max_length=40, verbose_name='city'),
        ),
    ]
