# Generated by Django 2.2 on 2019-04-12 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=40, verbose_name='标题')),
                ('intro', models.TextField(db_column='intro', verbose_name='简介')),
            ],
            options={
                'verbose_name': 'information',
                'verbose_name_plural': '相关信息',
                'db_table': 'information',
            },
        ),
        migrations.CreateModel(
            name='SubTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=50, verbose_name='子标题')),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_titles', to='information.Information')),
            ],
            options={
                'verbose_name': 'subtitle',
                'verbose_name_plural': '子标题',
                'db_table': 'subtitle',
            },
        ),
        migrations.CreateModel(
            name='SubContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(db_column='content', verbose_name='内容')),
                ('sub_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='information.SubTitle')),
            ],
            options={
                'verbose_name': 'sub_content',
                'verbose_name_plural': '子段落',
                'db_table': 'sub_content',
            },
        ),
        migrations.CreateModel(
            name='ListTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=50, verbose_name='列表标题')),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_titles', to='information.Information')),
            ],
            options={
                'verbose_name': 'list_title',
                'verbose_name_plural': '列表标题',
                'db_table': 'list_title',
            },
        ),
        migrations.CreateModel(
            name='ListContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(db_column='content', verbose_name='内容')),
                ('list_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='information.ListTitle')),
            ],
            options={
                'verbose_name': 'list_content',
                'verbose_name_plural': '列表段落',
                'db_table': 'list_content',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(db_column='content', verbose_name='内容')),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='information.Information')),
            ],
            options={
                'verbose_name': 'content',
                'verbose_name_plural': '段落',
                'db_table': 'informationContent',
            },
        ),
    ]
