# Generated by Django 2.2 on 2019-04-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=40, verbose_name='标题')),
                ('proper', models.CharField(db_column='proper', max_length=200, verbose_name='与年龄相当')),
                ('mild', models.CharField(db_column='mild', max_length=200, verbose_name='轻度异常')),
                ('moderate', models.CharField(db_column='moderate', max_length=200, verbose_name='中度异常')),
                ('badly', models.CharField(db_column='badly', max_length=200, verbose_name='严重异常')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': '测试题',
                'db_table': 'question',
            },
        ),
    ]
